site_name: Physpetools
pages:
- Home: index.md
- install: install.md
- Usage: usage.md
- Tutorial: tutorial.md
theme: mkdocs

repo_url: https://github.com/xiaofeiyangyang/physpetools
site_description:  a auto reconstruct phylogentic tools 
site_author: Yang Fang
